# For more info on HTTP files go to https://aka.ms/vs/httpfile

### Acceptable request
GET https://localhost:7246/Policies/1
Accept: application/json


### Should return 404 - Not Found
GET https://localhost:7246/Policies/9999
Accept: application/json

### Should return 400 - Bad Request
GET https://localhost:7246/Policies/abc
Accept: application/json

### - Should return all policies.
GET https://localhost:7246/Policies/
Accept: application/json

### Acceptable Request to create a new policy
POST https://localhost:7246/Policies/
content-type: application/json
{
  "PolicyNumber": "HSCX1006",
  "Premium": 100.00,
  "StartDate": "2024-01-01T00:00:00"
}

### Invalid Policy Number
POST https://localhost:7246/Policies/
content-type: application/json
{
  "PolicyNumber": "",
  "Premium": 150.00,
  "StartDate": "2024-01-01T00:00:00"
}

### Invalid Premium
POST https://localhost:7246/Policies/
content-type: application/json
{
  "PolicyNumber": "HSCX1006",
  "Premium": -50.00,
  "StartDate": "2024-01-01T00:00:00"
}

### Invalid Start Date
POST https://localhost:7246/Policies/
content-type: application/json
{
  "PolicyNumber": "HSCX1006",
  "Premium": 200.00,
  "StartDate": "2020/01/10 10:00"
}

### Valid Export request
GET https://localhost:7246/Policies/export?startDate=2024-04-01T00:00:00&endDate=2030-12-31T23:59:59
Accept: application/json

### Malformed export request
GET https://localhost:7246/Policies/export?endDate=2030-12-31T23:59:59
Accept: application/json

### REALLY malformed export request
GET https://localhost:7246/Policies/export?startDate=2024-04-aaaaaaaaaaaaaaaaaaa01T00:00:00&endDate=2030-12-31T23:59:59
Accept: application/json